In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pickle

In [3]:
# Load data
train_data = pd.read_csv('New_train.csv')

In [5]:
train_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [9]:
train_data = train_data[['MSSubClass', 'LotArea', 'HouseStyle', 'RoofStyle', 'TotalBsmtSF', 'FullBath', 'BedroomAbvGr', 'GarageCars', 'SalePrice']]

In [11]:
train_data.head()

,MSSubClass,LotArea,HouseStyle,RoofStyle,TotalBsmtSF,FullBath,BedroomAbvGr,GarageCars,SalePrice
0,60,8450,2Story,Gable,856,2,3,2,208500
1,20,9600,1Story,Gable,1262,2,3,2,181500
2,60,11250,2Story,Gable,920,2,3,2,223500
3,70,9550,2Story,Gable,756,1,3,3,140000
4,60,14260,2Story,Gable,1145,2,4,3,250000

In [15]:
train_data.dtypes

MSSubClass       int64
LotArea          int64
HouseStyle      object
RoofStyle       object
TotalBsmtSF      int64
FullBath         int64
BedroomAbvGr     int64
GarageCars       int64
SalePrice        int64
dtype: object

In [13]:
for col in train_data.columns:
    print('Unique values of ' + col)
    print(train_data[col].unique())
    print("======================")

Unique values of MSSubClass
[ 60  20  70  50 190  45  90 120  30  85  80 160  75 180  40]
======================
Unique values of LotArea
[ 8450  9600 11250 ... 17217 13175  9717]
======================
Unique values of HouseStyle
['2Story' '1Story' '1.5Fin' '1.5Unf' 'SFoyer' 'SLvl' '2.5Unf' '2.5Fin']
======================
Unique values of RoofStyle
['Gable' 'Hip' 'Gambrel' 'Mansard' 'Flat' 'Shed']
======================
Unique values of TotalBsmtSF
[ 856 1262  920  756 1145  796 1686 1107  952  991 1040 1175  912 1494
 1253  832 1004    0 1114 1029 1158  637 1777 1060 1566  900 1704 1484
  520  649 1228 1234 1398 1561 1117 1097 1297 1057 1088 1350  840  938
 1150 1752 1434 1656  736  955  794  816 1842  384 1425  970  860 1410
  780  530 1370  576 1143 1947 1453  747 1304 2223  845 1086  462  672
 1768  440  896 1237 1563 1065 1288  684  612 1013  990 1235  876 1214
  824  680 1588  960  458  950 1610  741 1226 1053  641  789  793 1844
  994 1264 1809 1028  729 1092 1125 1673  728  732 1080 1199 1362 1078
  660 1008  924  992 1063 1267 1461 1907  928  864 1734  910 1490 1728
  715  884  969 1710  825 1602 1200  572  774 1392 1232 1572 1541  882
 1149  644 1617 1582  720 1064 1606 1202 1151 1052 2216  968  504 1188
 1593  853  725 1431  855 1726 1360  755 1713 1121 1196  617  848 1424
 1140 1100 1157 1212  689 1070 1436  686  798 1248 1498 1010  713 2392
  630 1203  483 1373 1194 1462  894 1414  996 1694  735  540  626  948
 1845 1020 1367 1444 1573 1302 1314  975 1604  963 1482  506  926 1422
  802  740 1095 1385 1152 1240 1560 2121 1160  807 1468 1575  625  858
  698 1079  768  795 1416 1003  702 1165 1470 2000  700  319  861 1896
  697  972 2136  716 1347 1372 1249 1136 1502 1162  710 1719 1383  844
  596 1056 3206 1358  943 1499 1922 1536 1208 1215  967  721 1684  536
  958 1478  764 1848 1869  616  624  940 1142 1062  888  883 1394 1099
 1268  953  744  608  847  683  870 1580 1856  982 1026 1293  939  784
 1256  658 1041 1682  804  788 1144  961 1260 1310 1141  806 1281 1034
 1276 1340 1344  988  651 1518  907  901  765  799  648 3094 1440 1258
  915 1517  930  813 1533  872 1242 1364  588  709  560 1375 1277 1626
 1488  808  547 1976 2153 1705 1833 1792 1216  999 1113 1073  954  264
 1269  190 3200  866 1501  777 1218 1368 1084 2006 1244 3138 1379 1257
 1452  528 2035  611  707  880 1051 1581 1838 1650  723  654 1204 1069
 1709  998  993 1374 1389 1163 1122 1496  846  372 1164 1050 2042 1868
 1437  742  770 1722 1814 1430 1058  908  600  965 1032 1299 1120  936
  783 1822 1522  980 1116  978 1156  636 1554 1386  811 1520 1952 1766
  981 1094 2109  525  776 1486 1629 1138 2077 1406 1021 1408  738 1477
 2046  923 1291 1195 1190  874  551 1419 2444 1210  927 1112 1391 1800
  360 1473 1643 1324  270  859  718 1176 1311  971 1742  941 1698 1584
 1595  868 1153  893 1349 1337 1720 1479 1030 1318 1252  983 1860  836
 1935 1614  761 1413  956  712  650  773 1926  731 1417 1024  849 1442
 1649 1568  778 1489 2078 1454 1516 1067 1559 1127 1390 1273  918 1763
 1090 1054 1039 1148 1002 1638  105  676 1184 1109  892 2217 1505 1059
  951 2330 1670 1623 1017 1105 1001  546  480 1134 1104 1272 1316 1126
 1181 1753  964 1466  925 1905 1500  585 1632  819 1616 1161  828  945
  979  561  696 1330  817 1098 1428  673 1241  944 1225 1266 1128  485
 1930 1396  916  822  750 1700 1007 1187  691 1574 1680 1346  985 1657
  602 1022 1082  810 1504 1220 1132 1565 1338 1654 1620 1055  800 1306
 1475 2524 1992 1193  973  854  662 1103 1154  942 1048  727  690 1096
 1459 1251 1247 1074 1271  290  655 1463 1836  803  833  408  533 1012
 1552 1005 1530  974 1567 1006 1042 1298  704  932 1219 1296 1198  959
 1261 1598 1683  818 1600 2396 1624  831 1224  663  879  815 1630 2158
  931 1660  559 1300 1702 1075 1361 1106 1476 1689 2076  792 2110 1405
 1192  746 1986  841 2002 1332  935 1019  661 1309 1328 1085 6110 1246
  771  976 1652 1278 1902 1274 1393 1622 1352  420 1795  544 1510  911
  693 1284 1732 2033  570 1980  814  873  757 1108 2633 1571  984 1205
  714 1746 1525  482 1356  862  839 1286 1485 1594  622  791  708 1223
  913  656 1319 1932  539 1221 1542]
======================
Unique values of FullBath
[2 1 3 0]
======================
Unique values of BedroomAbvGr
[3 4 1 2 0 5 6 8]
======================
Unique values of GarageCars
[2 3 1 0 4]
======================
Unique values of SalePrice
[208500 181500 223500 140000 250000 143000 307000 200000 129900 118000
 129500 345000 144000 279500 157000 132000 149000  90000 159000 139000
 325300 139400 230000 154000 256300 134800 306000 207500  68500  40000
 149350 179900 165500 277500 309000 145000 153000 109000  82000 160000
 170000 130250 141000 319900 239686 249700 113000 127000 177000 114500
 110000 385000 130000 180500 172500 196500 438780 124900 158000 101000
 202500 219500 317000 180000 226000  80000 225000 244000 185000 144900
 107400  91000 135750 136500 193500 153500 245000 126500 168500 260000
 174000 164500  85000 123600 109900  98600 163500 133900 204750 214000
  94750  83000 128950 205000 178000 118964 198900 169500 100000 115000
 190000 136900 383970 217000 259500 176000 155000 320000 163990 136000
 153900 181000  84500 128000  87000 150000 150750 220000 171000 231500
 166000 204000 125000 105000 222500 122000 372402 235000  79000 109500
 269500 254900 162500 412500 103200 152000 127500 325624 183500 228000
 128500 215000 239000 163000 184000 243000 211000 501837 200100 120000
 475000 173000 135000 153337 286000 315000 192000 148500 311872 104000
 274900 171500 112000 143900 277000  98000 186000 252678 156000 161750
 134450 210000 107000 311500 167240 204900  97000 386250 290000 106000
 192500 148000 403000  94500 128200 216500  89500 185500 194500 318000
 262500 110500 241500 137000  76500 276000 151000  73000 175500 179500
 120500 266000 124500 201000 415298 228500 244600 179200 164700  88000
 153575 233230 135900 131000 167000 142500 175000 158500 267000 149900
 295000 305900  82500 360000 165600 119900 375000 188500 270000 187500
 342643 354000 301000 126175 242000 324000 145250 214500  78000 119000
 284000 207000 228950 377426 202900  87500 140200 151500 157500 437154
 318061  95000 105900 177500 134000 280000 198500 147000 165000 162000
 172400 134432 123000  61000 340000 394432 179000 187750 213500  76000
 240000  81000 191000 426000 106500 129000  67000 241000 245500 164990
 108000 258000 168000 339750  60000 222000 181134 149500 126000 142000
 206300 275000 109008 195400  85400  79900 122500 212000 116000  90350
 555000 162900 199900 119500 188000 256000 161000 263435  62383 188700
 124000 178740 146500 187000 440000 251000 132500 208900 380000 297000
  89471 326000 374000 164000  86000 133000 172785  91300  34900 430000
 226700 289000 208300 164900 202665  96500 402861 265000 234000 106250
 184750 315750 446261 200624 107500  39300 111250 272000 248000 213250
 179665 229000 263000 112500 255500 121500 268000 325000 316600 135960
 142600 224500 118500 146000 131500 181900 253293 369900  79500 185900
 451950 138000 319000 114504 194201 217500 221000 359100 313000 261500
  75500 137500 183200 105500 314813 305000 165150 139900 209500  93000
 264561 274000 370878 143250  98300 205950 350000 145500  97500 197900
 402000 423000 230500 173500 103600 257500 372500 159434 285000 227875
 148800 392000 194700 755000 335000 108480 141500  89000 123500 138500
 196000 312500 361919 213000  55000 302000 254000 179540  52000 102776
 189000 130500 159500 341000 103000 236500 131400  93500 239900 299800
 236000 265979 260400 275500 158900 179400 215200 337000 264132 216837
 538000 134900 102000 395000 221500 175900 187100 161500 233000 107900
 160200 146800 269790 143500 485000 582933 227680 135500 159950 144500
  55993 157900 224900 271000 224000 183000 139500 232600 147400 237000
 139950 174900 133500 189950 250580 248900 169000 200500  66500 303477
 132250 328900 122900 154500 118858 142953 611657 125500 255000 154300
 173733  75000  35311 238000 176500 145900 169990 193000 117500 184900
 253000 239799 244400 150900 197500 172000 116500 214900 178900  37900
  99500 182000 167500  85500 178400 336000 159895 255900 117000 395192
 195000 197000 348000 173900 337500 121600 206000 232000 136905 119200
 227000 203000 213490 194000 287000 293077 310000 119750  84000 315500
 262280 278000 139600 556581  84900 176485 200141 185850 328000 167900
 151400  91500 138800 155900  83500 252000  92900 176432 274725 134500
 184100 133700 118400 212900 163900 259000 239500  94000 424870 174500
 116900 201800 218000 235128 108959 233170 245350 625000 171900 154900
 392500 745000 186700 104900 262000 219210 116050 271900 229456  80500
 137900 367294 101800 138887 265900 248328 465000 186500 169900 171750
 294000 165400 301500  99900 128900 183900 378500 381000 185750  68400
 150500 281000 333168 206900 295493 111000 156500  72500  52500 155835
 108500 283463 410000 156932 144152 216000 274300 466500  58500 237500
 377500 246578 281213 137450 193879 282922 257000 223000 274970 182900
 192140 143750  64500 394617 149700 149300 121000 179600  92000 287090
 266500 142125 147500]
======================

In [17]:
# Initialize a dictionary to store LabelEncoders for each categorical column
label_encoders = {}

# Categorical columns that need encoding
categorical_columns = ['MSSubClass', 'HouseStyle', 'RoofStyle']

In [19]:
# Fit and transform the categorical columns
for col in categorical_columns:
    le = LabelEncoder()
    train_data[col] = le.fit_transform(train_data[col])
    label_encoders[col] = le  # Store the encoder for later use

    # Print the encoded values for each category
    print(f'Encoded values for {col}:')
    for index, class_ in enumerate(le.classes_):
        print(f'{class_}: {index}')
    print()  # Add a newline for better readability

Encoded values for MSSubClass:
20: 0
30: 1
40: 2
45: 3
50: 4
60: 5
70: 6
75: 7
80: 8
85: 9
90: 10
120: 11
160: 12
180: 13
190: 14

Encoded values for HouseStyle:
1.5Fin: 0
1.5Unf: 1
1Story: 2
2.5Fin: 3
2.5Unf: 4
2Story: 5
SFoyer: 6
SLvl: 7

Encoded values for RoofStyle:
Flat: 0
Gable: 1
Gambrel: 2
Hip: 3
Mansard: 4
Shed: 5

In [21]:
# Features and target variable
X = train_data.drop('SalePrice', axis=1)  # Features
y = train_data['SalePrice']  # Target variable

# Scale numerical features
scaler = StandardScaler()
numeric_columns = ['LotArea', 'TotalBsmtSF', 'FullBath', 'BedroomAbvGr', 'GarageCars']
train_data[numeric_columns] = scaler.fit_transform(train_data[numeric_columns])

In [23]:
print(train_data.head())

   MSSubClass   LotArea  HouseStyle  RoofStyle  TotalBsmtSF  FullBath  \
0           5 -0.207142           5          1    -0.459303  0.789741
1           0 -0.091886           2          1     0.466465  0.789741
2           5  0.073480           5          1    -0.313369  0.789741
3           6 -0.096897           5          1    -0.687324 -1.026041
4           5  0.375148           5          1     0.199680  0.789741

   BedroomAbvGr  GarageCars  SalePrice
0      0.163779    0.311725     208500
1      0.163779    0.311725     181500
2      0.163779    0.311725     223500
3      0.163779    1.650307     140000
4      1.390023    1.650307     250000

In [31]:
from sklearn.ensemble import RandomForestRegressor  # Ensure this import is included
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Choose and train a Random Forest Regressor
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Calculate the evaluation metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (RÂ²): {r2}")

# Save the model
with open('House_Price_Prediction.pkl', 'wb') as file:
    pickle.dump(model, file)

print("Model saved as 'random_forest_model.pkl'")

Mean Absolute Error (MAE): 23984.24330153294
Mean Squared Error (MSE): 1298638696.8613458
Root Mean Squared Error (RMSE): 36036.6299320753
R-squared (RÂ²): 0.8306931593542246

In [49]:
import pandas as pd
import pickle
from sklearn.preprocessing import StandardScaler

# Load the saved model
with open('House_Price_Prediction.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

# Example of new data - ensure these values match your feature engineering in training
new_data = pd.DataFrame({
    'MSSubClass': [60],        # Example value
    'LotArea': [8450],         # Example value
    'HouseStyle': ['1Story'],  # Example value
    'RoofStyle': ['Gable'],    # Example value
    'TotalBsmtSF': [856],      # Example value
    'FullBath': [2],           # Example value
    'BedroomAbvGr': [3],       # Example value
    'GarageCars': [2]          # Example value
})

# Preprocessing for new data

# 1. Encode categorical features
# Assuming you used one-hot encoding during training
new_data = pd.get_dummies(new_data, columns=['HouseStyle', 'RoofStyle'], drop_first=True)

# Add missing columns if any were generated during one-hot encoding in the training set
expected_columns = loaded_model.feature_names_in_
for col in expected_columns:
    if col not in new_data.columns:
        new_data[col] = 0

# Ensure the order of columns is the same
new_data = new_data[expected_columns]

# 2. Scale numerical features
numeric_columns = ['LotArea', 'TotalBsmtSF', 'FullBath', 'BedroomAbvGr', 'GarageCars']
scaler = StandardScaler()

# Apply the scaler that was used during training (use transform instead of fit_transform)
new_data[numeric_columns] = scaler.fit_transform(new_data[numeric_columns])

# Make predictions
new_predictions = loaded_model.predict(new_data)

# Print predictions
print(f"Predicted Price: ${new_predictions[0]:,.2f}")

Predicted Price: $67,904.67